image:
  pullPolicy: IfNotPresent
  repository: photoprism/photoprism
  tag: "20221021"
password: "admin123"
environmentVariables: []
extraAppVolumeMounts: []
web_port: 32000
dnsConfig:
  options: []
emptyDirVolumes: true
appVolumeMounts:
  original:
    emptyDir: true
    mountPath: /photoprism/originals
  storage:
    emptyDir: true
    mountPath: /photoprism/storage
  import:
    emptyDir: true
    mountPath: /photoprism/import
ownerUID: 568
ownerGID: 568
public: false
